version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=metric-app
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - postgres
    build: ./backend
    container_name: metric-backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_USERNAME=user
      - DB_HOST=postgres
      - DB_DATABASE=metric-app
      - DB_PASSWORD=postgres_password
      - DB_PORT=5432
  frontend:
    depends_on:
      - backend
    build: ./frontend
    container_name: metric-frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
